apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJVMmhsY25Ob2RXdHZkanBuYVhSb2RXSmZjR0YwWHpFeFFVcEVVRVZPU1RCalUxZGxVbmd3U2xoVE1XTmZRMHBXUmtGNWEwUkdVVFJDTjJJNWJGb3lWMEZDVjBaRU9FdEVTemhPWmpoNk4yeEdTamhwU1V0S2EwdElWRVJUV2tGSk1YWkRXbWxuTTJnPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
